# Generated by Django 5.1.4 on 2024-12-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
    ]
